name: JFrog Snapshot Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup jdk zulu
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        server-id: snapshots   # snapshot server id (maybe jfrog dependency)
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: deploy to jfrog
      run: |
        ./mvnw clean site install
        ./mvnw -U -PpruefeVersionen,release clean site install
        ./mvnw -Pjfrog --batch-mode
      env:
        MAVEN_USERNAME: ${{ secrets.OSSJF_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSJF_TOKEN }}

        

